package clienteWs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-11-30T20:52:01.998-02:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "IntegracionService", 
                  wsdlLocation = "http://186.55.71.146:8080/JattrickCentral-ejb/integracion?wsdl",
                  targetNamespace = "http://tsi201.com/") 
public class IntegracionService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tsi201.com/", "IntegracionService");
    public final static QName IntegracionPort = new QName("http://tsi201.com/", "integracionPort");
    static {
        URL url = null;
        try {
            url = new URL("http://186.55.71.146:8080/JattrickCentral-ejb/integracion?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IntegracionService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://186.55.71.146:8080/JattrickCentral-ejb/integracion?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IntegracionService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IntegracionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IntegracionService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IntegracionService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IntegracionService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IntegracionService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Integracion
     */
    @WebEndpoint(name = "integracionPort")
    public Integracion getIntegracionPort() {
        return super.getPort(IntegracionPort, Integracion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Integracion
     */
    @WebEndpoint(name = "integracionPort")
    public Integracion getIntegracionPort(WebServiceFeature... features) {
        return super.getPort(IntegracionPort, Integracion.class, features);
    }

}
