package com.tsi201;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-11-22T13:36:53.221-02:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://tsi201.com/", name = "integracion")
@XmlSeeAlso({ObjectFactory.class})
public interface Integracion {

    @WebMethod
    @RequestWrapper(localName = "play", targetNamespace = "http://tsi201.com/", className = "com.tsi201.Play")
    @ResponseWrapper(localName = "playResponse", targetNamespace = "http://tsi201.com/", className = "com.tsi201.PlayResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.tsi201.JRequestMatchDTO play(
        @WebParam(name = "arg0", targetNamespace = "")
        com.tsi201.TeamDTO arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.Integer arg1
    );

    @WebMethod
    @RequestWrapper(localName = "ping", targetNamespace = "http://tsi201.com/", className = "com.tsi201.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://tsi201.com/", className = "com.tsi201.PingResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String ping();

    @WebMethod
    @RequestWrapper(localName = "getTeams", targetNamespace = "http://tsi201.com/", className = "com.tsi201.GetTeams")
    @ResponseWrapper(localName = "getTeamsResponse", targetNamespace = "http://tsi201.com/", className = "com.tsi201.GetTeamsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.tsi201.TeamDTO> getTeams();
}
