package otro;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-11-22T13:57:01.233-02:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "IntegracionServiciosService", 
                  wsdlLocation = "http://192.168.1.42:8080/servicios_jatrik/IntegracionServicios?wsdl",
                  targetNamespace = "http://api/") 
public class IntegracionServiciosService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://api/", "IntegracionServiciosService");
    public final static QName IntegracionServiciosPort = new QName("http://api/", "IntegracionServiciosPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.1.42:8080/servicios_jatrik/IntegracionServicios?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IntegracionServiciosService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.1.42:8080/servicios_jatrik/IntegracionServicios?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IntegracionServiciosService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IntegracionServiciosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IntegracionServiciosService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IntegracionServiciosService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IntegracionServiciosService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IntegracionServiciosService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IntegracionServicios
     */
    @WebEndpoint(name = "IntegracionServiciosPort")
    public IntegracionServicios getIntegracionServiciosPort() {
        return super.getPort(IntegracionServiciosPort, IntegracionServicios.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IntegracionServicios
     */
    @WebEndpoint(name = "IntegracionServiciosPort")
    public IntegracionServicios getIntegracionServiciosPort(WebServiceFeature... features) {
        return super.getPort(IntegracionServiciosPort, IntegracionServicios.class, features);
    }

}
