package otro;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2014-11-22T13:57:01.199-02:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://api/", name = "IntegracionServicios")
@XmlSeeAlso({ObjectFactory.class})
public interface IntegracionServicios {

    @WebMethod
    @RequestWrapper(localName = "listarEquipos", targetNamespace = "http://api/", className = "otro.ListarEquipos")
    @ResponseWrapper(localName = "listarEquiposResponse", targetNamespace = "http://api/", className = "otro.ListarEquiposResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<otro.EquipoIntegracion> listarEquipos();

    @WebMethod
    @RequestWrapper(localName = "jugarPartido", targetNamespace = "http://api/", className = "otro.JugarPartido")
    @ResponseWrapper(localName = "jugarPartidoResponse", targetNamespace = "http://api/", className = "otro.JugarPartidoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public otro.ResultadoIntegracionDto jugarPartido(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        otro.EquipoIntegracion arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        otro.AlineacionIntegracion arg2
    );
}
